apiVersion: v1
items:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    labels:
      app: inventory
    name: inventory
    namespace: toast
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: inventory:latest
    runPolicy: Serial
    source:
      contextDir: OpenshiftServer/Microservices/inventory
      git:
        uri: https://github.com/art200109/ToastApp.git
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: python:3.6
          namespace: openshift
      type: Source
    triggers:
    - github:
        secret: nbcrxqC9Bu1x64B_I0TV
      type: GitHub
    - generic:
        secret: eNr7DezJ-MDAGCaAfbvw
      type: Generic
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    labels:
      app: login
    name: login
    namespace: toast
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: login:latest
    runPolicy: Serial
    source:
      contextDir: OpenshiftServer/Microservices/login
      git:
        uri: https://github.com/art200109/ToastApp.git
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: python:3.6
          namespace: openshift
      type: Source
    triggers:
    - github:
        secret: 8CCJnWsMgAmb-HgSNgCC
      type: GitHub
    - generic:
        secret: oL_6hTuTiTj_LJpu_KFI
      type: Generic
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    labels:
      app: menu
    name: menu
    namespace: toast
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: menu:latest
    runPolicy: Serial
    source:
      contextDir: OpenshiftServer/Microservices/menu
      git:
        uri: https://github.com/art200109/ToastApp.git
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: python:3.6
          namespace: openshift
      type: Source
    triggers:
    - github:
        secret: 6Un3wrBM2-6BssH2gYdb
      type: GitHub
    - generic:
        secret: Rjk2ImCsjM3espxYlnJ7
      type: Generic
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    labels:
      app: order
    name: order
    namespace: toast
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: order:latest
    runPolicy: Serial
    source:
      contextDir: OpenshiftServer/Microservices/order
      git:
        uri: https://github.com/art200109/ToastApp.git
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: python:3.6
          namespace: openshift
      type: Source
    triggers:
    - github:
        secret: louD2ABriEk8qzPax8ps
      type: GitHub
    - generic:
        secret: LbC0nZ7Fjn1bbSBCeEPt
      type: Generic    
- kind: "Service"
  apiVersion: "build.openshift.io/v1"
  metadata:
    name: "external-mysql-service"
  spec:
    ports:
      -
        name: "mysql"
        protocol: "TCP"
        port: 27017
        targetPort: 27017 
        nodePort: 0
  selector: {}
- kind: "Endpoints"
  apiVersion: "build.openshift.io/v1"
  metadata:
    name: "external-mysql-service" 
  subsets: 
    -
      addresses:
        -
          ip: "<<mongo_ip>>" 
      ports:
        -
          port: 27017 
          name: "mysql"
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
